#!/bin/sh

ENABLED=yes

DESC="Open Source Conditional Access Module service"
PROCS="oscam"
PROG="/opt/bin/$PROCS"

start_pre() {
  [ -d "/opt/var/log/$PROCS/cw" ] || \
  mkdir -pm 0750 /opt/var/log/"$PROCS"/cw
}

PRECMD="start_pre"
ARGS="-b"
PREARGS=""

. /opt/etc/init.d/rc.func
