#!/bin/sh

ENABLED=no

DESC="RSS torrents downloader daemon"
PROCS="automatic"
PROG="/opt/bin/$PROCS"

LOGFILE="/opt/var/log/$PROCS.log"

start_pre() {
  [ -w "$LOGFILE" ] || touch "$LOGFILE"
}

PRECMD="start_pre"
ARGS="-l $LOGFILE -a"
PREARGS=""

. /opt/etc/init.d/rc.func
