#!/bin/sh

ENABLED=yes

DESC="Pure-FTPd server"
PROCS="pure-ftpd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
}

PRECMD="start_pre"
ARGS="/opt/etc/$PROCS.conf"
PREARGS=""

. /opt/etc/init.d/rc.func
