#!/bin/sh

ENABLED=yes

DESC="UrBackup Server"
PROCS="urbackupsrv"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/run/urbackup.pid"

start_pre() {
  rm -f "$PID_FILE"
  . /opt/lib/functions.sh
  user_exists urbackup || user_add urbackup 5555
  group_exists urbackup || group_add urbackup 5555
  for i in \
    /opt/var/lib/urbackup \
    /opt/var/log/urbackup
  do
    [ -d "$i" ] || {
      mkdir -pm 0750 "$i"
      chgrp urbackup "$i"
    }
  done
}

PRECMD="start_pre"
ARGS="run -c /opt/etc/urbackup/urbackup.cfg -d -w $PID_FFILE"
PREARGS=""

. /opt/etc/init.d/rc.func
