#!/bin/sh

ENABLED=yes

DESC="Policy routing daemon"
PROCS="pingu"
PROG="/opt/sbin/$PROCS"

start_pre() {
  rm -f /opt/var/run/$PROCS.ctl
}

PRECMD="start_pre"
ARGS="-d"
PREARGS=""

. /opt/etc/init.d/rc.func
