#!/bin/sh

ENABLED=yes

DESC="eXtensible UPnP agent (2)"
PROCS="xupnpd2"
PROG="/opt/sbin/$PROCS"

start_pre() {
  [ -d "/opt/var/lib/$PROCS" ] || \
  mkdir -pm 0750 /opt/var/lib/"$PROCS"
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
