#!/bin/sh

ENABLED=yes

DESC="Pixel webserver"
PROCS="pixelserv-tls"
PROG="/opt/bin/$PROCS"

start_pre() {
  [ -d "/opt/var/cache/pixelserv" ] || \
  mkdir -pm 0750 /opt/var/cache/pixelserv
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
