#!/bin/sh

ENABLED=yes

DESC="Deluge Web interface"
PROCS="deluge-web"
PROG="/opt/bin/$PROCS"

LIMIT="15"
PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
}

PRECMD="start_pre"
ARGS="-l /opt/var/log/$PROCS.log -L error -p 888 -P $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
