#!/bin/sh

ENABLED=yes

DESC="IRC proxy"
PROCS="bip"
PROG="/opt/bin/$PROCS"

PID_FILE="/opt/var/lib/$PROCS/$PROCS.pid"

start_pre() {
  rm -f "$PID_FILE"
  [ -d "/opt/var/lib/$PROCS" ] || \
  mkdir -pm 0750 /opt/var/lib/"$PROCS"
}

PRECMD="start_pre"
ARGS="-f /opt/etc/$PROCS.conf -s /opt/var/lib/$PROCS"
PREARGS=""

. /opt/etc/init.d/rc.func
