#!/bin/sh

ENABLED=yes

DESC="inotify cron daemon"
PROCS="incrond"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
  [ -d "/opt/var/spool/incron" ] || \
  mkdir -pm 0750 /opt/var/spool/incron
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
