#!/bin/sh

ENABLED=yes

DESC="Alaya Webdav Server"
PROCS="alaya"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
