#!/bin/sh

ENABLED=yes

DESC="Shell In A Box terminal emulator"
PROCS="shellinaboxd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
}

PRECMD="start_pre"
ARGS="-t -u root --css /opt/lib/shellinabox/white-on-black.css -b --pidfile=$PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
