#!/bin/sh

ENABLED=yes

DESC="DNS proxy and translator for IPv4/6"
PROCS="totd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

start_pre() {
  rm -f "PID_FILE"
}

PRECMD="start_pre"
ARGS=""
PREARGS=""

. /opt/etc/init.d/rc.func
